### ISSUE TITLE
configure with --disable-ios --disable-ios-device fails

### ISSUE THREAD

**Issue by Therzok** [dotnet/macios#14201]
### Steps to Reproduce

1. `./configure --disable-ios --disable-ios-device --enable-dotnet`
2. `make`
3. Observe the build fails

### Expected Behavior

Build succeeds.

### Actual Behavior
Makefile dependency error is reported

### Build Logs

```
make[1]: *** No rule to make target `/Users/therzok/Work/md/xamarin-macios/_ios-build/Library/Frameworks/Mono.framework/External/xbuild/Xamarin', needed by `/Users/therzok/Work/md/xamarin-macios/_ios-build/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/MacCatalyst'.  Stop.
```

### Workaround

Editing `configure.inc` to have `INCLUDE_MACCATALYST=` doesn't fully do the trick.

<details>
<summary>Error</summary>

```
/Users/therzok/Work/md/xamarin-macios/builds/downloads/dotnet-sdk-6.0.300-preview.22116.1-osx-x64/sdk/6.0.300-preview.22116.1/MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/therzok/Work/md/xamarin-macios/builds/downloads/dotnet-sdk-6.0.300-preview.22116.1-osx-x64/sdk/6.0.300-preview.22116.1/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/therzok/Work/md/xamarin-macios/builds/downloads/dotnet-sdk-6.0.300-preview.22116.1-osx-x64/sdk/6.0.300-preview.22116.1/dotnet.dll -maxcpucount -restore -target:pack -verbosity:m -verbosity:quiet /bl FrameworksInRuntimesNativeDirectory.csproj
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018: The "CreateFrameworkListFile" task failed unexpectedly.
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018: System.IO.FileNotFoundException: /Users/therzok/Work/md/xamarin-macios/tests/test-libraries/frameworks/.libs/maccatalyst-x64/FrameworksInRuntimesNativeDirectory1.framework.zip
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at Microsoft.DotNet.SharedFramework.Sdk.FileUtilities.GetFileVersion(String sourcePath) in /_/src/Microsoft.DotNet.SharedFramework.Sdk/src/FileUtilities.cs:line 23
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at Microsoft.DotNet.SharedFramework.Sdk.CreateFrameworkListFile.<>c.<Execute>b__24_3(ITaskItem item) in /_/src/Microsoft.DotNet.SharedFramework.Sdk/src/CreateFrameworkListFile.cs:line 82
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at System.Linq.GroupedEnumerable`2.GetEnumerator()
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at Microsoft.DotNet.SharedFramework.Sdk.CreateFrameworkListFile.Execute() in /_/src/Microsoft.DotNet.SharedFramework.Sdk/src/CreateFrameworkListFile.cs:line 80
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/Users/therzok/Work/md/xamarin-macios/tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj(93,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
make[4]: *** [.libs/FrameworksInRuntimesNativeDirectory.nupkg] Error 1
make[3]: *** [all-recurse] Error 1
make[2]: *** [all-recurse] Error 1
make[1]: *** [all-recurse] Error 1
make: *** [all-recurse] Error 1
```

</details>

Should `INCLUDE_MACCATALYST` also be written when `INCLUDE_IOS` is disabled?

**Comment by Therzok** [comment]
`--disable-ios-device` fails as well, with this:

```
Rolling back pack Microsoft.iOS.Sdk installation...
Rolling back pack Microsoft.iOS.Ref installation...
Rolling back pack Microsoft.iOS.Runtime.ios-arm installation...
Workload installation failed: microsoft.ios.runtime.ios-arm::15.2.302-ci.ui-thread-gen.34 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dar
c-pub-dotnet-runtime-6dd808ff-1/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaging/macios-dependencies/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json;/Users/therzok/Work/md/xamarin-macios/_build/nupkgs".
Description:
  Install one or more workloads.
```

Will do a normal configure build. :D

**Comment by rolfbjarne** [comment]
The configure option `--disable-ios-device` has been removed, so this doesn't apply anymore.
