### ISSUE TITLE
DllNotFoundException thrown ONLY on mac catalyst release mode on arm64

### ISSUE THREAD

**Issue by borrrden** [dotnet/macios#21594]
### Apple platform

Mac Catalyst

### Framework version

net8.0-*

### Affected platform version

.NET 8.0.403

### Description

I develop a nuget package that has a native framework inside of it.  I've been developing a testing application for various platforms (including mac catalyst) that makes use of the package.  I don't have an Apple Silicon mac, so I've been developing it on my Intel mac where everything works just as expected.  However, as soon as I bring it over to Apple Silicon the same exact program crashes with `DllNotFoundException` UNLESS I run it through rosetta to use the x86_64 variant, or run a debug build.   

I have verified the following:

- Both the main binary and the framework are inside of the app bundle, and contain slices for both x86_64 and arm64
- The RPATH of the main binary is set to `@executable_path/../Frameworks`
- `otool -L` shows that the main binary is linked with the framework

I suppose this means it has something to do with AOT compilation?  Here are some of the references to what I am doing.  I use the nuget package called Couchbase.Lite.Enterprise where I make use of 100+ DllImport calls such as this one:

https://github.com/couchbase/couchbase-lite-net/blob/5302dba59ae4bacef39f2a33d173d1edc8909616/src/LiteCore/src/LiteCore.Shared/Interop/C4Log_native.cs#L38

You can see that the name of the library is defined as "LiteCore" https://github.com/couchbase/couchbase-lite-net/blob/5302dba59ae4bacef39f2a33d173d1edc8909616/src/LiteCore/src/LiteCore.Shared/Constants.cs#L24

Furthermore, for the benefit of iOS / mac catalyst (not sure actually if this is needed or not anymore) I set up a resolver function to remap this to `@rpath/LiteCore.framework/LiteCore`:

https://github.com/couchbase/couchbase-lite-net/blob/5302dba59ae4bacef39f2a33d173d1edc8909616/src/LiteCore/src/LiteCore.Shared/Interop/NativeActivate.cs#L39-L41

This works just fine for iOS simulator, ios device, mac catalyst x64 in any config, and mac catalyst arm64 in debug.  However running a release build on arm64 crashes immediately and I see in the output:

```
*** Terminating app due to uncaught exception 'System.TypeInitializationException', reason: 'TypeInitialization_Type, Couchbase.Lite.Database (System.TypeInitializationException)
   at TestServer.MauiProgram.CreateMauiApp()
   at TestServer.AppDelegate.CreateMauiApp()
   at Microsoft.Maui.MauiUIApplicationDelegate.WillFinishLaunching(UIApplication application, NSDictionary launchOptions)
LiteCore (System.DllNotFoundException)
   at Couchbase.Lite.Logging.FileLogger.SetupDomainObjects()
   at Couchbase.Lite.Logging.FileLogger..ctor()
   at Couchbase.Lite.Logging.Log..ctor()
   at Couchbase.Lite.Database..cctor()
```

Which lines up to the first time a DllImport function is called here https://github.com/couchbase/couchbase-lite-net/blob/5302dba59ae4bacef39f2a33d173d1edc8909616/src/Couchbase.Lite.Shared/API/Database/Database.cs#L255

I'm not even sure what I can do to debug this, let alone get any further information but it would be nice if it ran without crashing.

### Steps to Reproduce

1. Create a new mac catalyst project on Apple Silicon
2. Add the Couchbase.Lite.Enterprise nuget package
3. Add something like `var db = new Database("test")` inside the app delegate finished launching function
4. Make a release build and try to run the main binary directly (i.e. `app.app/Contents/MacOS/app`)

### Did you find any workaround?

Don't compile for arm64 (leave it out of the runtime identifiers)

**Comment by rolfbjarne** [comment]
> Furthermore, for the benefit of iOS / mac catalyst (not sure actually if this is needed or not anymore) I set up a resolver function to remap this to `@rpath/LiteCore.framework/LiteCore`:
> 
> [couchbase/couchbase-lite-net@`5302dba`/src/LiteCore/src/LiteCore.Shared/Interop/NativeActivate.cs#L39-L41](https://github.com/couchbase/couchbase-lite-net/blob/5302dba59ae4bacef39f2a33d173d1edc8909616/src/LiteCore/src/LiteCore.Shared/Interop/NativeActivate.cs#L39-L41)

Is the resolve function executed at all on Mac Catalyst/x64?

That said, I think the first question would be: is the `LiteCore` library where it's supposed to be?

You can figure that out by looking at the files in the app bundle (might have to fix the path slightly depending on your build settings):

```
$ find ./bin/Release/*.app/
```

and there should be one file among the result like this:  `app.app/Contents/Frameworks/LiteCore.framework/LiteCore`.

If that's not the case, then please provide an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs), because it sounds like a build issue.

If the library _is_ there, then it might be a problem where the OS refuses to load it.

One way to figure this out is to open the library manually, and checking the error afterwards:

```cs
using ObjCRuntime;

static void CheckLibrary ()
{
	var rv = Dlfcn.dlopen ("@rpath/LiteCore.framework/LiteCore", Dlfcn.Mode.Now);
    if (rv == IntPtr.Zero) {
		var error = Dlfcn.dlerror ();
		Console.WriteLine ("Failed to load library: {error}");
	} else {
		Console.WriteLine ("Loaded library successfully");
	}
}
```

and then where to go from here depends on the actual error.

**Comment by borrrden** [comment]
Ok here is what I have found from looking into what you said.  The library is for sure in the location:

I assume that the resolve function is being used, because using just "LiteCore" as a DllImport name on mac catalyst throws a DllNotFoundException on x64.  It HAS to be the rpath variant.  

```
ls -l tmp.app/Contents/Frameworks/LiteCore.framework
total 0
lrwxr-xr-x@ 1 mobile  staff   24 Nov  8 13:57 Headers -> Versions/Current/Headers
lrwxr-xr-x@ 1 mobile  staff   25 Nov  8 13:57 LiteCore -> Versions/Current/LiteCore
lrwxr-xr-x@ 1 mobile  staff   24 Nov  8 13:57 Modules -> Versions/Current/Modules
lrwxr-xr-x@ 1 mobile  staff   26 Nov  8 13:57 Resources -> Versions/Current/Resources
drwxr-xr-x@ 4 mobile  staff  128 Oct 29 14:37 Versions
```

Interestingly, running your code for dlopen I got random errors that were just garbage, but a library that refused to load.  Then I tried using the absolute path and I got "Library loaded successfully".  I took this back to my x64 machine and the rpath variant worked fine without converting it to an absolute path.  This may be where the fault lies.

**Comment by borrrden** [comment]
One more interesting piece of info...the following works on arm64 as well:

`@executable_path/../Frameworks/LiteCore.framework/LiteCore`

**Comment by borrrden** [comment]
All that being said, it still insta-crashes in Release mode....

```
Translated Report (Full Report Below)
-------------------------------------

Process:               tmp [22250]
Path:                  /Users/USER/*/tmp.app/Contents/MacOS/tmp
Identifier:            com.couchbase.tmp
Version:               1.0 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-11-08 14:35:02.8679 -0800
OS Version:            macOS 15.1 (24B83)
Report Version:        12
Anonymous UUID:        8B8315C5-9D89-2CF4-D715-9F792DE18801


Time Awake Since Boot: 340000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  tid_103  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   tmp [22250]

Application Specific Information:
abort() called


Thread 0 Crashed:: tid_103 Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x19903a600 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x199072f70 pthread_kill + 288
2   libsystem_c.dylib             	       0x198f7f908 abort + 128
3   tmp                           	       0x104d60ef8 sigabrt_signal_handler.cold.1 + 48 (mini-posix.c:226)
4   tmp                           	       0x104d21de0 sigabrt_signal_handler + 196 (mini-posix.c:224)
5   libsystem_platform.dylib      	       0x1990a8184 _sigtramp + 56
6   libsystem_pthread.dylib       	       0x199072f70 pthread_kill + 288
7   libsystem_c.dylib             	       0x198f7f908 abort + 128
8   tmp                           	       0x104b5c43c mono_log_write_os_log + 408 (mono-log-darwin.c:58)
9   tmp                           	       0x104b5164c monoeg_g_logstr + 44 (goutput.c:151) [inlined]
10  tmp                           	       0x104b5164c monoeg_g_logv_nofree + 136 (goutput.c:166) [inlined]
11  tmp                           	       0x104b5164c monoeg_g_logv + 172 (goutput.c:173)
12  tmp                           	       0x104b51794 monoeg_g_log + 28 (goutput.c:182)
13  tmp                           	       0x104cc3468 load_aot_module + 4272 (aot-runtime.c:2365)
14  tmp                           	       0x104bb14d8 mono_assembly_invoke_load_hook_internal + 92 (assembly.c:1081) [inlined]
15  tmp                           	       0x104bb14d8 mono_assembly_request_load_from + 1104 (assembly.c:2020)
16  tmp                           	       0x104bb0ff8 mono_assembly_request_open + 472 (assembly.c:1625)
17  tmp                           	       0x104bb2c90 mono_assembly_open + 88 (assembly.c:1828)
18  tmp                           	       0x104a27d9c xamarin_assembly_preload_hook + 452 (monotouch-main.m:157)
19  tmp                           	       0x104bb2ec8 invoke_assembly_preload_hook + 76 (assembly.c:1283)
20  tmp                           	       0x104bb074c netcore_load_reference + 480 (assembly.c:827) [inlined]
21  tmp                           	       0x104bb074c mono_assembly_request_byname + 1012 (assembly.c:2786)
22  tmp                           	       0x104ccd2f8 load_image + 280 (aot-runtime.c:325)
23  tmp                           	       0x104cc3400 load_aot_module + 4168 (aot-runtime.c:2357)
24  tmp                           	       0x104cc7e54 load_container_amodule + 180 (aot-runtime.c:2489) [inlined]
25  tmp                           	       0x104cc7e54 mono_aot_get_method + 312 (aot-runtime.c:4920)
26  tmp                           	       0x104c685c8 mono_jit_compile_method_with_opt + 440 (mini-runtime.c:2758) [inlined]
27  tmp                           	       0x104c685c8 jit_compile_method_with_opt_cb + 452 (mini-runtime.c:2879) [inlined]
28  tmp                           	       0x104c685c8 jit_compile_method_with_opt + 552 (mini-runtime.c:2895)
29  tmp                           	       0x104c6caec mono_jit_compile_method_jit_only + 40 (mini-runtime.c:2933) [inlined]
30  tmp                           	       0x104c6caec mono_jit_runtime_invoke + 540 (mini-runtime.c:3525)
31  tmp                           	       0x104c10da4 do_runtime_invoke + 60 (object.c:2576) [inlined]
32  tmp                           	       0x104c10da4 mono_runtime_invoke_checked + 148 (object.c:2792)
33  tmp                           	       0x104bce2ec create_exception_two_strings + 592 (exception.c:176)
34  tmp                           	       0x104bce070 mono_exception_from_name_two_strings_checked + 148 (exception.c:236)
35  tmp                           	       0x104bad0e8 create_domain_objects + 88 (appdomain.c:192) [inlined]
36  tmp                           	       0x104bad0e8 mono_runtime_init_checked + 712 (appdomain.c:288)
37  tmp                           	       0x104c6c3c4 mini_init + 6692 (mini-runtime.c:4886)
38  tmp                           	       0x104cbf85c mono_jit_init_version + 20 (driver.c:2823)
39  tmp                           	       0x104a272c0 xamarin_bridge_initialize + 164 (monovm-bridge.m:88)
40  tmp                           	       0x104a28024 xamarin_main + 256 (monotouch-main.m:436)
41  tmp                           	       0x104d60b04 main + 64 (main.arm64.mm:220)
42  dyld                          	       0x198cf0274 start + 2840
```

**Comment by rolfbjarne** [comment]
I'm not sure what's going on here; is there any chance you can create a test project I can use to reproduce the problem?

**Comment by borrrden** [comment]
I am sort of thinking this is just simply bad rpath handling by the operating system.  Oddly, after going back to test this again it randomly started working at some point (maybe some kind of caching...) but here is the project that I use for reproduction by watching the console output via the Console app:

[LiteCoreTest.zip](https://github.com/user-attachments/files/17822294/LiteCoreTest.zip)

Just tweak the path used in the dlopen call to see various results.  Make sure you are building arm64 on arm64, and not any sort of x64 variant.

I did find a workaround, which is to only build x64 and let Rosetta handle things.  I don't want to rely on that for the long term though.

**Comment by borrrden** [comment]
Oh my goodness that was a blunder on my part.  I was wondering why the int returned from dlerror seemed so strange (it's a pointer).  I was afraid it would work for you and not for me.  Yes this is only in release mode where AOT is working that the problem shows and sometimes, oddly, it doesn't show.  

So by works you mean that you've run the maccatalyst-arm64 variant with AOT enabled and the console printed "Loaded library successfully"?  I'll see what is happening today on the arm mac that I have access to.

**Comment by borrrden** [comment]
I can't get this to happen anymore so now I am wondering why I had to waste a day on this.  Very frustrating.  You can close if you like and I will re-open if I happen to see it again.

**Comment by rolfbjarne** [comment]
> I can't get this to happen anymore so now I am wondering why I had to waste a day on this. Very frustrating. You can close if you like and I will re-open if I happen to see it again.

Yes, chasing issues that eventually go away by themselves can be quite frustrating.

We'll be glad to try to help if the problem pops up again.

Happy coding!

**Comment by borrrden** [comment]
It's happening to me again, but not on the test project.  I tried on my real project and the result is that dlopen works just fine and then the app crashes anyway with the DllNotFoundException.  I have a sneaking suspicion that the dllimportresolver is not functioning correctly.  I had a similar issue with iOS back in the day that was solved by turning on the "Interpreter" but that doesn't have an effect in this case.
