### ISSUE TITLE
Detecting certificate challenge in NSUrlSessionHandler

### ISSUE THREAD

**Issue by mstefarov** [dotnet/macios#21688]
I'm building cross-platform auth components, which include client-certificate (PKI) authentication.  Currently only SocketsHttpHandler is fully functional, but I would like to support NSUrlSessionHandler as well.

The work on https://github.com/xamarin/xamarin-macios/issues/13856 got me most of the way there, but one problem remains: detecting when a server challenges my client for a client certificate.  In the past the norm used to be to look for HTTP/401 or 403 replies, but now many TLS/SSLv3-secured services use [error alerts](https://www.rfc-editor.org/rfc/rfc5246#section-7.2.2) instead.  This happens when the connection is still negotiated so I have no HttpResponseMessage to work with &mdash; all I have is an HttpRequestException.

With **SocketsHttpHandler on iOS**, I have options.  I can subscribe to LocalCertificateSelectionCallback and listen for events, or I can check HttpRequestException's InnerException (of type Interop+AppleCrypto+SslException) gives me a specific libsecurity error code via HResult.  I can check if it matches e.g. [errSSLPeerBadCert (-9825)](https://github.com/apple-oss-distributions/libsecurity_ssl/blob/540c9a25ea94be4415b2315c8a3f5124a6639036/lib/SecureTransport.h#L210) and prompt user for a client certificate.  

With vanilla NSUrlSession I can look for challenges with [AuthenticationMethodClientCertificate](https://learn.microsoft.com/en-us/dotnet/api/foundation.nsurlprotectionspace.authenticationmethodclientcertificate?view=xamarin-ios-sdk-12) protection space.

But with NSUrlSessionHandler, this challenge is doomed to fail unless I [pre-load a correct certificate ahead of time](https://github.com/xamarin/xamarin-macios/blob/1a2b3e386303c35c71ecc4bfc228aa15f23607f2/src/Foundation/NSUrlSessionHandler.cs#L1101-L1110), and I end up with a fairly generic "connection lost" HttpRequestException: 

```
System.Net.Http.HttpRequestException: The network connection was lost.
 ---> Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=-4, NSUnderlyingError=0x600000c4cd20 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" ...}
   --- End of inner exception stack trace ---
   at System.Net.Http.NSUrlSessionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSUrlSessionHandler.cs:line 551
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

I might be able to workaround this by e.g. falling back to SocketHttpHandler when I see that "network connection lost" error to double-check if this is a certificate challenge. But my life would be a lot easier if NSUrlSessionHandler itself could help detect a challenge, either by providing a client-certificate-selection callback, or by providing a more detailed error message.

P.S. I also made a similar request for SocketHttpHandler-on-Android in https://github.com/dotnet/runtime/issues/109532

**Comment by rolfbjarne** [comment]
@mandel-macaque can you look at this?

**Comment by dotMorten** [comment]
Some initial findings of behavior today. Consider the following scenario where you check that a certificate is required, and then repeat the request by pre-loading the certificate (pre-loading a certificate already works after PR I submitted last year):

```cs
  using var client = new HttpClient(nsurlhandler, true);
  try
  {
      await client.GetStringAsync(url);
  }
  catch (Exception ex)
  {
      if (IsCertificateFailure(ex)) // How do we implement this?
      {
          RetryWithCertificate();
          return;
      }
      throw;
  }
```
The question is: How do we detect the exception thrown is specifically a certificate? With SocketsHttpHandler, we can tell from the inner exceptions, but with NSUrlSessionHandler we just get a generic inner `NSErrorException` from iOS stating "The network connection was lost". 

In NSUrlSessionHandler.NSUrlSessionHandlerDelegate::DidReceiveChallengeImpl this is is called 6 times, first time with Auth-Scheme `NSURLAuthenticationMethodServerTrust`, second time with `NSURLAuthenticationMethodClientCertificate` (which is the one we need to handle), and then repeat these two, two more times until it fails.

It fails because this line returns null (as expected since we haven't added any certificates): https://github.com/dotnet/macios/blob/6882a52f2d9f1eca6e92407911682edd3a84d5d9/src/Foundation/NSUrlSessionHandler.cs#L1146
My guess is we need to handle if this is null and fail the request in a predictable manner.
